### ISSUE TITLE
Northflank external img

### ISSUE THREAD

**Issue by sedaryildirim** [Golumpa/hoyolab-auto-login#1]
Hello,

came across your repo and was trying to get it to work with ZZZ.

when on northflank and entering the img url, it doesnt validate and just asks to verify your credentials.

any solution to this? thank you regardless.

**Comment by Golumpa** [comment]
I'll look into this today as I didn't make those instructions, it was the previous repo as this is a fork.

**Comment by sedaryildirim** [comment]
> I'll look into this today as I didn't make those instructions, it was the previous repo as this is a fork.

Thank you, no problem if its not fixable, just saw your repo and i liked it as its very helpful for me. appreciate your reply none the less.

**Comment by Golumpa** [comment]
> > I'll look into this today as I didn't make those instructions, it was the previous repo as this is a fork.
> 
> Thank you, no problem if its not fixable, just saw your repo and i liked it as its very helpful for me. appreciate your reply none the less.

I believe the issue was you were using the image from the screenshot and not from the text, the screenshots are the exact same as the old repo so it had the old repo image URL in there which is now gone.

I changed the image to use this repo's image now to stop confusion

**Comment by sedaryildirim** [comment]
Thank you! apologies for my mistake! all working now!
